version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27018:27017
    volumes:
      - ~/apps/mongo-cards:/data/db-cards
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_ROOT_DATABASE=cards